baseURL: "https://soyomarvaldezg.xyz"
languageCode: en-us
title: Omar Valdez G
theme: PaperMod
pagination:
  pagerSize: 5

enableRobotsTXT: true
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: Omar Valdez G
  Description:
  author: Omar Valdez G
  description: "#dataengineering #datainfra #ai #dataintegrity #dataops #security"
  keywords: [blog, soyomarvaldezg, papermod]
  defaultTheme: dark
  disableThemeToggle: true
  enableComments: true
  cusdisAppId: ""
  social: true
  profileMode:
    enabled: true
    title: "Omar Valdez G"
    subtitle: ""
    imageUrl: "profile.png"
    imageTitle: "Omar Valdez G"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: "blog posts"
        url: "/posts/"
      - name: ">_ whoami"
        url: "/whoami/"
      - name: "eBook"
        url: "https://payhip.com/b/6zilp"

  label:
    icon: "favicon/favicon.ico"
    iconHeight: 35
    text: "~$ cd .."

  # homeInfoParams:
  #   Title: "Omar Valdez G"

  socialIcons:
    - name: "youtube"
      url: "https://youtube.com/@soyomarvaldezg"
    - name: "linkedin"
      url: "https://linkedin.com/in/soyomarvaldezg"
    - name: "twitter"
      url: "https://x.com/soyomarvaldezg"
    - name: "github"
      url: "https://github.com/soyomarvaldezg"
    - name: "instagram"
      url: "https://instagram.com/soyomarvaldezg"
    - name: "tiktok"
      url: "https://tiktok.com/@soyomarvaldezg"
    - name: "spotify"
      url: "https://open.spotify.com/show/2RtBQW42FpVTViB7uMnAvQ"

  assets:
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"
    safari_pinned_tab: "favicon/favicon-16x16.png"

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  UseHugoToc: false
  showtoc: true
  tocopen: true
  hideSummary: false
  comments: true

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

menu:
  main:
    - name: ðŸ”Ž search
      url: "/search/"
      weight: 4
    - name: â€¢ dotfiles
      url: "/dotfiles/"
      weight: 5
    - name: â€¢ tags
      url: /tags/
      weight: 6
    - name: â€¢ posts
      url: /posts/
      weight: 7
